[book]
authors = ["Skerples", "Lasse Borly"]
language = "da"
multilingual = false
src = "src"
title = "Slangekongernes Grav"

[output.html]
additional-css = ["src/assets/styles/lightbox.css"]
additional-js = ["src/assets/scripts/lightbox.js"]
no-section-label = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
