[book]
authors = ["Skerples", "Lasse Borly"]
language = "da"
multilingual = false
src = "src"
title = "Slangekongernes Grav"

[output.html]
additional-css = ["src/styles/lightbox.css"]
additional-js = ["src/scripts/lightbox.js"]
