/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'introduktion',
      label: 'Introduktion',
    },
    {
      type: 'doc',
      id: 'kort',
      label: 'Kort',
    },
    {
      type: 'category',
      label: 'Den Falske Grav',
      items: [
        {
          type: 'doc',
          id: 'den_falske_grav/forhallen',
          label: '1: Forhallen'
        },
        {
          type: 'doc',
          id: 'den_falske_grav/vogtergravene',
          label: '2: Vogtergravene'
        },
        {
          type: 'doc',
          id: 'den_falske_grav/de_lærdes_grav',
          label: '3: De Lærdes Grav'
        }
      ]
    },
    {
      type: 'category',
      label: 'Den Øvre Grav',
      items: [
        {
          type: 'doc',
          id: 'den_øvre_grav/stenstøtternes_hal',
          label: '9: Stenstøtternes Hal'
        },
        {
          type: 'doc',
          id: 'den_øvre_grav/hemmeligt_vagtkammer',
          label: '10: Hemmeligt Vagtkammer'
        },
        {
          type: 'doc',
          id: 'den_øvre_grav/grav_atrium',
          label: '11: Grav Atrium'
        }
      ]
    },
    {
      type: 'category',
      label: 'Den Nedre Grav',
      link: {type: 'doc', id: 'den_nedre_grav/den_nedre_grav'},
      items: [
        {
          type: 'doc',
          id: 'den_nedre_grav/stendør',
          label: '22: Stendør'
        },
        {
          type: 'doc',
          id: 'den_nedre_grav/cerimonikammer',
          label: '23: Cerimonikammer'
        },
        {
          type: 'doc',
          id: 'den_nedre_grav/korridor',
          label: '24: Korridor'
        }
      ]
    },
    {
      type: 'category',
      label: 'Uhyrer',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'uhyrer',
        }
      ]
    }
  ],
};

module.exports = sidebars;
